config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#top'
  get 'home/about'
  resources :blogs ,only: [:index, :new, :create, :show, :destroy, :edit, :update]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  attachment :image
  acts_as_taggable

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  enum status: { draft: 0, published: 1, deleted: 2 }
  validates :status, inclusion: { in: Blog.statuses.keys }

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

 def after_sign_in_path_for(resource) 
   new_blog_path
 end
  def after_sign_up_path_for(resource)
  new_blog_path
 end

 def after_sign_out_path_for(resource)
  root_path 
 end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
 def new
  @blog = Blog.new
end
def create
  @blog = current_user.blogs.new(blogs_params)
  if @blog.save
    flash[:notice] = "投稿完了しました！"
    redirect_to user_path(current_user.id)
  else
    render :new
  end 
end 
def index
  @blogs = Blog.all
  if params[:tag_name]
    @blogs = Blog.tagged_with("#{params[:tag_name]}")
  end
end
def show
  @blog = Blog.find(params[:id])
  if (@blog.published? || @blog.user_id = current_user.id && @blog.draft?)
    render "show"
  else
    flash[:alert] = "非公開です "
    redirect_to root_path
  end
end
def edit
  @blog = Blog.find(params[:id])
  if @blog.user.id == current_user.id 
    render "edit"
  else
    redirect_to root_path
  end
end
def update
  @blog = Blog.find(params[:id])

  if @blog.update(blogs_params)
    flash[:notice] = "投稿編集完了しました！"
    redirect_to user_path(current_user.id)
  else
    render :edit
  end
end
def destroy
  @blogs = Blog.find(params[:id])
  @blogs.destroy
  redirect_to user_path(current_user.id)
end

private
def blogs_params
  params.require(:blog).permit(:title, :body, :image, :start_time, :tag_list, :tag_name, :address, :status)
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def top
 end
 def about
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!
 def show
 @user = User.find(params[:id])
 @blogs = @user.blogs.page(params[:page]).reverse_order # ここを記述
 if params[:tag_name]
   @blogs = Blog.tagged_with("#{params[:tag_name]}")
 end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<div class="container">
  <div class = "row">
    <div class = "col-lg-2">
    </div>
    <div class = "col-lg-8">
      <h1>編集画面</h1>
      <%= form_for(@blog) do |f| %>
        <% if @blog.errors.any? %>
          <%= @blog.errors.count %>件のエラーがあります
          <% @blog.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <br><%= f.label :タイトル %>

        <%= f.text_field :title, class:"form-control",placeholder: "題名"%>

        <%= f.label :本文 %>
        <%= f.text_area :body, class:"form-control input-lg", rows:"13", placeholder: "本文" %>
        

        <%= f.label :start_time %>
        <%= f.datetime_select :start_time %>

        <br><%= f.label :tag %>
        <%= f.text_field :tag_list, value: @blog.tag_list.join(','), class:"form-control", placeholder: "例）旅、休日、温泉"  %>

        <br><%= f.label :場所 %>
        <%= f.text_field :address, class:"form-control", placeholder: "場所" %>

        <br><label>公開ステータス</label>
        <%= f.select :status, [["非公開", "draft"],["公開", "published"]], id: "status" %>

        <h4>画像</h4>
        
        <%= f.attachment_field :image, id: :user_img %>
          <% if @blog.image.present? %>
          <%= attachment_image_tag @blog, :image, size: "1000x400", fallback: "sample.png" , id: "img_prev"%>
          <% else %>
            <%= image_tag "sample.png", id: :img_prev %>
          <% end %>


          <script type="text/javascript">
            $(function() {
              function readURL(input) {
                  if (input.files && input.files[0]) {
                  var reader = new FileReader();
                  reader.onload = function (e) {
              $('#img_prev').attr('src', e.target.result);
                  }
                  reader.readAsDataURL(input.files[0]);
                  }
              }
              $("#user_img").change(function(){
                readURL(this);
              });
            });
          </script>
          <br><%= f.submit '投稿',class:"btn btn-primary form-control" %>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<br>
<br>
<br>
<br>

<h1>(タグ別）投稿一覧</h1>
<table class="table">
  <thead>
    <tr>
      <td>title</td>
      <td>date</td>
      <td>tag</td>
      <td>status</td>
    </tr>
  <thead>
  <% @blogs.each do |blog| %>
    <tbody>
      <tr>
        <td><%= link_to blog.title,blog_path(blog.id) %></td>
        <td><%= blog.start_time.strftime("%Y-%m-%d %H:%M") %></td>
        <td><% blog.tag_list.each do |tag| %>
              <%= link_to tag, blogs_path(tag_name: tag), class: "badge badge-secondary"%>
            <% end %></td>
        <td><% if blog.status == "draft" %>
              非公開
            <% else %>
              公開
            <% end %></td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/blogs/new.html.erb
<div class="container">
  <div class = "row">
    <div class = "col-lg-2">
    </div>
    <div class = "col-lg-8">
      <h1>新規投稿</h1>
      <%= form_for(@blog) do |f| %>
        <% if @blog.errors.any? %>
          <%= @blog.errors.count %>件のエラーがあります
          <% @blog.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <br><%= f.label :タイトル %>

        <%= f.text_field :title, class:"form-control",placeholder: "題名"%>


        <%= f.label :本文 %>
        <%= f.text_area :body, class:"form-control input-lg", rows:"13", placeholder: "本文" %>
        

        <%= f.label :start_time %>
        <%= f.datetime_select :start_time %>

        <br><%= f.label :tag %>
        <%= f.text_field :tag_list, value: @blog.tag_list.join(','), class:"form-control", placeholder: "例）旅、休日、温泉"  %>

        <br><%= f.label :場所 %>
        <%= f.text_field :address, class:"form-control", placeholder: "場所" %>

        <br><label>公開ステータス</label>
        <%= f.select :status, [["非公開", "draft"],["公開", "published"]], id: "status" %>

        <h4>画像</h4>
        <%= f.attachment_field :image, id: :user_img %>
          <% if @blog.image.present? %>
            <%= image_tag @blog.image, id: :img_prev %>
          <% else %>
            <%= image_tag "sample.png", id: :img_prev %>
          <% end %>


          <script type="text/javascript">
            $(function() {
              function readURL(input) {
                  if (input.files && input.files[0]) {
                  var reader = new FileReader();
                  reader.onload = function (e) {
              $('#img_prev').attr('src', e.target.result);
                  }
                  reader.readAsDataURL(input.files[0]);
                  }
              }
              $("#user_img").change(function(){
                readURL(this);
              });
            });
          </script>
          <br><%= f.submit '投稿',class:"btn btn-primary form-control" %>
          
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="container">
  <div class = "row">
    <div class = "col-lg-2">
    </div>
    <div class = "col-lg-8">
      <h3><div class="border"><%= @blog.title %></div></h3>
      <br><h5><div class="tbody"><%= @blog.body %></div></h5>
      <%= attachment_image_tag @blog, :image, size: "700x400", fallback: "sample.png" %>
      <script>
        function initMap() {
          var test ={lat: <%= @blog.latitude %>, lng: <%= @blog.longitude %>};
          var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 15, 
                    center: test
                    });x
          var transitLayer = new google.maps.TransitLayer();
          transitLayer.setMap(map);

          var contentString = '住所：<%= @blog.address %>';
          var infowindow = new google.maps.InfoWindow({
            content: contentString
          });

          var marker = new google.maps.Marker({
                        position:test,
                        map: map,
                        title: contentString
                      });

          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });
        }
      </script>


      <script async defer
                    src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyByyWf7N-cyT5NtcdHAlhYcIafd1UJyJrU&callback=initMap">
      </script>
      <div id="map"></div>
      <style>
      #map{
        height: 400px;
      }
      </style>

      <br><%= link_to "Edit",edit_blog_path(@blog.id),class:"btn btn-success" %>
      <%= link_to "Destroy", blog_path(@blog.id),class:"btn btn-danger" ,method: :delete, "data-confirm" => "Are you sure?" %>
      <%= @blog.start_time.strftime("%Y-%m-%d %H:%M") %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
  <div class = "row">
    <div class = "col-lg-2">
    </div>
    <div class = "col-lg-8">
     
      <h1>Welcome to<span class="glyphicon glyphicon-book" aria-hidden="true"></span>OMB Blogs!</h1>
      <br><h3>OMB Blog とは Only For Myself Blog<br><br>の略で自分自身専用のブログサービスです</h3>
      <div class ="tyuui">
        <h4>投稿したブログをシェアしたい場合は公開ステータスを公開にし、記事のURLを教えれば<br>シェアできます。
        （すでに投稿したブログはeditページで操作できます）</h4>
      </div>
    </div>
  </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class = "tops">
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="row">
      <div class="top-message col-md-offset-3 col-md-6">
        <h1>welcome to <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>OMB Blog!!</h1>

        <p>非公開型ブログのブログサービスです。登録/ログインは⬇️から</p>
        <br>
        <br>
        <%= link_to "Log In", new_user_session_path, class:"btn btn-info col-xs-10 col-xs-offset-1 bottons "%>
        <br>
        <br>
        <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1 "%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OMBServis2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container relative">
    <nav>
      <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li class="">
            <%= link_to ' マイページ', user_path(current_user.id), class: 'glyphicon glyphicon-user users' %></li>
          <li class="">
            <%= link_to ' 新規投稿', new_blog_path, class: 'glyphicon glyphicon-list-alt' %></li>
          <li class="">
            <%= link_to " ログアウト", destroy_user_session_path, method: :delete , class: 'glyphicon glyphicon-log-out'%>
          <% else %>
          <li class="">
            <%= link_to "Home", root_path , class: "glyphicon glyphicon-home home" %></li>
          <li class="">
            <%= link_to "About", home_about_path , class: "glyphicon glyphicon-home home" %></li>
          <li class="">
            <%= link_to "Sign up",new_user_registration_path, class:"glyphicon glyphicon-edit" %></li>
          <li class="">
            <%= link_to " Log in", new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>
<div class = "main">
<%= yield %>
</div>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class = "row">
    <div class = "col-lg-2">
    </div>
    <div class = "col-lg-8">
      <% if flash[:notice] %>
        <div class="flash">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <%= month_calendar events: @blogs do |date, blogs| %>
        <%= date.day %>
      
        <% blogs.each do |blog| %>
          <div>
            <%= link_to blog.title, blog %>
          </div>
        <% end %>
      <% end %>

      <h1>投稿一覧</h1>
        <table class="table">
          <thead>
            <tr>
              <td>title</td>
              <td>date</td>
              <td>tag</td>
              <td>status</td>
            </tr>
          <thead>
          <% @blogs.each do |blog| %>
            <tbody>
              <tr>
                <td><%= link_to blog.title,blog_path(blog.id) %></td>
                <td><%= blog.start_time.strftime("%Y-%m-%d %H:%M") %></td>
                <td><% blog.tag_list.each do |tag| %>
                      <%= link_to tag, blogs_path(tag_name: tag), class: "badge badge-secondary"%>
                    <% end %></td>
                <td><% if blog.status == "draft" %>
                      非公開
                    <% else %>
                      公開
                    <% end %></td>
              </tr>
            </tbody>
          <% end %>
          <%= paginate @blogs %>
        </table>
          
    </div>
  </div>
</div>